name: CX#_workflow
on: 
  push: 
    branches: 
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: chekout code
        uses: actions/chekout@v3
        
      - name: Setup Node.js
        uses:  actions/setup-node@v3
        with:
          node-verion: 18
          
      - name: install dependency
        run: npm install

      - name: test code 
        run: npm test
